---
permalink: technical-reports/monitor/alerts-monitoring.html 
sidebar: sidebar 
keywords: alerts, storagegrid 
summary: Saiba como usar o sistema de alertas no StorageGRID para monitorar problemas, gerenciar alertas personalizados e estender notificações de alerta via SNMP ou e-mail. 
---
= Use alertas para monitorar o StorageGRID
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../../media/


[role="lead"]
Saiba como usar o sistema de alertas no StorageGRID para monitorar problemas, gerenciar alertas personalizados e estender notificações de alerta usando SNMP ou e-mail.

Os alertas fornecem informações críticas que lhe permitem monitorizar os vários eventos e condições no seu sistema StorageGRID.

O sistema de alertas foi projetado para ser a principal ferramenta para monitorar quaisquer problemas que possam ocorrer em seu sistema StorageGRID. O sistema de alertas se concentra em problemas acionáveis no sistema e fornece uma interface fácil de usar.

Fornecemos uma variedade de regras de alerta padrão que visam ajudar a monitorar e solucionar problemas do seu sistema. Você pode gerenciar ainda mais alertas criando alertas personalizados, editando ou desativando alertas padrão e silenciando notificações de alerta.

Os alertas também são extensíveis através de notificações SNMP ou por e-mail.

Para obter mais informações sobre alertas, consulte o https://docs.netapp.com/us-en/storagegrid-118/monitor/managing-alerts-and-alarms.html["documentação do produto"^] disponível on-line e em formato PDF.
