---
permalink: technical-reports/monitor/index.html 
sidebar: sidebar 
keywords: monitoring, storagegrid 
summary: Conheça o NetApp StorageGRID, suas condições de erro e como monitorá-lo de forma eficaz usando aplicativos externos, como o Splunk. 
---
= Introdução ao monitoramento StorageGRID
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../../media/


[role="lead"]
Saiba como monitorar seu sistema StorageGRID usando aplicativos externos, como o Splunk.

O monitoramento eficaz do storage baseado em objeto do NetApp StorageGRID permite que os administradores respondam rapidamente a problemas urgentes e adicionem recursos proativamente para lidar com workloads crescentes. Este relatório fornece orientações gerais sobre como monitorar as principais métricas e como aproveitar os aplicativos de monitoramento externos. Destina-se a complementar o guia de monitorização e resolução de problemas existente.

Uma implantação do NetApp StorageGRID geralmente consiste em vários locais e muitos nós que operam para criar um sistema de storage de objetos distribuído e tolerante a falhas. Em um sistema de storage distribuído e resiliente, como o StorageGRID, é normal que existam condições de erro enquanto a grade continua operando normalmente. O desafio para você, como administrador, é entender o limite no qual as condições de erro (como nós para baixo) apresentam um problema que deve ser imediatamente resolvido versus informações que devem ser analisadas. Ao analisar os dados que o StorageGRID apresenta, você entende seu workload e toma decisões informadas, como quando adicionar mais recursos.

O StorageGRID fornece uma excelente documentação que se aprofunda no assunto do monitoramento. Este relatório pressupõe que você está familiarizado com o StorageGRID e que você revisou a documentação sobre ele. Em vez de repetir essas informações, nos referimos à documentação do produto ao longo deste guia. A documentação do produto StorageGRID está disponível online e em formato PDF.

O objetivo deste documento é complementar a documentação do produto e discutir como monitorar o sistema StorageGRID usando aplicativos externos, como o Splunk.



== Fontes de dados

Para monitorar com sucesso o NetApp StorageGRID, é importante saber onde coletar dados sobre a integridade e as operações do seu sistema StorageGRID.

* * Interface Web e Painel de Controle.* O Gerenciador de Grade do StorageGRID apresenta uma visualização de nível superior das informações que você, como administrador, precisa ver em uma apresentação lógica. Como administrador, você também pode aprofundar as informações de nível de serviço para solução de problemas e coleções de log.
* *Logs de auditoria.* O StorageGRID mantém logs de auditoria granular de ações de locatários, como COLOCAR, OBTER e EXCLUIR. Você também pode rastrear o ciclo de vida de um objeto desde a ingestão até a aplicação de regras de gerenciamento de dados.
* *Metrics API.* Subjacente ao StorageGRID GMI estão APIs abertas, já que a IU é orientada pela API. Essa abordagem permite extrair dados usando ferramentas externas de monitoramento e análise.




== Onde encontrar informações adicionais

Para saber mais sobre as informações descritas neste documento, consulte os seguintes documentos e/ou sites:

* Centro de Documentação do NetApp StorageGRID https://docs.netapp.com/us-en/storagegrid-118/[]
* Capacitação NetApp StorageGRID https://docs.netapp.com/us-en/storagegrid-enable/[]
* Documentação do produto NetApp https://www.netapp.com/support-and-training/documentation/[]
* Aplicação NetApp StorageGRID para Splunk https://splunkbase.splunk.com/app/3898/#/details[]

