---
sidebar: sidebar 
permalink: technical-reports/data-security-index.html 
keywords: security features, storagegrid 
summary: Descubra os recursos de segurança integrais da solução de storage de objetos StorageGRID. 
---
= Proteja os dados e metadados do StorageGRID em um armazenamento de objetos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Descubra os recursos de segurança integrais da solução de storage de objetos StorageGRID.

Esta é uma visão geral dos muitos recursos de segurança do NetApp® StorageGRID®, abrangendo acesso a dados, objetos e metadados, acesso administrativo e segurança da plataforma.  Ele foi atualizado para incluir os recursos mais recentes lançados com o StorageGRID 12.0.

A segurança é parte integrante da solução de storage de objetos da NetApp StorageGRID. A segurança é particularmente importante porque muitos tipos de dados ricos em conteúdo que são adequados para armazenamento de objetos também são sensíveis por natureza e sujeitos a regulamentos e conformidade. À medida que os recursos do StorageGRID continuam a evoluir, o software disponibiliza muitos recursos de segurança que são inestimáveis para proteger a postura de segurança de uma organização e ajudar a organização a aderir às melhores práticas do setor.

Este artigo é uma visão geral dos muitos recursos de segurança do StorageGRID 12.0, divididos em cinco categorias:

* Recursos de segurança de acesso a dados
* Recursos de segurança de objetos e metadados
* Recursos de segurança de administração
* Recursos de segurança da plataforma
* Integração com a nuvem


Este documento pretende ser uma folha de dados de segurança; ele não detalha como configurar o sistema para oferecer suporte aos recursos de segurança enumerados que não são configurados por padrão.  O https://docs.netapp.com/us-en/storagegrid/harden/index.html["Guia de endurecimento da StorageGRID"^] está disponível no site oficial https://docs.netapp.com/us-en/storagegrid/["Documentação do StorageGRID"^] página.

Além dos recursos descritos neste relatório, o StorageGRID segue o https://www.netapp.com/us/legal/vulnerability-response.aspx["Política de notificação e resposta a vulnerabilidades de Segurança do produto NetApp"^]. Vulnerabilidades relatadas são verificadas e respondidas de acordo com o processo de resposta a incidentes de segurança do produto.

O NetApp StorageGRID fornece recursos avançados de segurança para casos de uso de storage de objetos empresarial altamente exigentes.



== Onde encontrar informações adicionais

Para saber mais sobre as informações descritas neste documento, consulte os seguintes documentos e/ou sites:

* NetApp StorageGRID: SEC 17a-4(f), FINRA 4511(c) e CFTC 1,31(c)-(d) avaliação de conformidade https://www.netapp.com/media/9041-ar-cohasset-netapp-storagegrid-sec-assessment.pdf[]
* Certificação de criptografia de kernel NetApp StorageGRID NIST FIPS 140-3 https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/5097[]
* Certificação de Entropia NetApp StorageGRID NIST SP 800-90B https://csrc.nist.gov/projects/cryptographic-module-validation-program/entropy-validations/certificate/223[]
* NetApp StorageGRID - Certificação de Critérios Comuns do Centro Canadense de Segurança Cibernética https://www.commoncriteriaportal.org/nfs/ccpfiles/files/epfiles/565-LSS%20CT%20v1.0.pdf[]
* Página de documentação do StorageGRIDhttps://docs.netapp.com/us-en/storagegrid/[]
* Documentação do produto NetApp https://www.netapp.com/support-and-training/documentation/[]




== Termos e acrônimos

Esta seção fornece definições para a terminologia usada no documento.

[cols="40,60"]
|===
| Termo ou acrônimo | Definição 


| S3 | Simple Storage Service. 


| Cliente | Um aplicativo que pode fazer interface com o StorageGRID através do protocolo S3 para acesso a dados ou protocolo HTTP para gerenciamento. 


| Administrador do locatário | O administrador da conta de locatário do StorageGRID 


| Utilizador inquilino | Um usuário dentro de uma conta de locatário do StorageGRID 


| TLS | Segurança da camada de transporte 


| ILM | Gerenciamento do ciclo de vida da informação 


| LAN | Rede local 


| Administrador de grade | O administrador do sistema StorageGRID 


| Grelha | O sistema StorageGRID 


| Balde | Um recipiente para objetos armazenados em S3 


| LDAP | Lightweight Directory Access Protocol 


| SEG | Comissão de valores Mobiliários; regula os membros do câmbio, corretores ou revendedores 


| FINRA | Autoridade reguladora da indústria financeira; defensa o formato e os requisitos de Mídia da regra SEC 17a-4(f) 


| CFTC | Comissões de negociação de futuros de commodities; regula a negociação de futuros de commodities 


| NIST | Instituto Nacional de normas e tecnologia 
|===