---
sidebar: sidebar 
permalink: technical-reports/commvault/index.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: Explore alguns casos de uso para configurações do StorageGRID implementadas pelos clientes e PELA TI DA NetApp. 
---
= Faça backup e recupere dados usando o StorageGRID e o CommVault
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
A CommVault e a NetApp fizeram uma parceria para criar uma solução de proteção de dados conjunta que combina o software CommVault Complete Backup and Recovery for NetApp com o software NetApp StorageGRID para storage de nuvem. O CommVault Complete Backup and Recovery e o NetApp StorageGRID oferecem soluções exclusivas e fáceis de usar que trabalham juntas para ajudar você a atender às demandas de crescimento rápido de dados e aumento das regulamentações no mundo todo.

Muitas organizações querem migrar o storage para a nuvem, escalar os sistemas e automatizar a política para retenção de dados a longo prazo. O storage de objetos baseado em nuvem é conhecido por sua resiliência, capacidade de escala e eficiências operacionais e de custo que o tornam uma escolha natural como destino para o seu backup. A CommVault e a NetApp juntas certificaram sua solução combinada em 2014 e, desde então, desenvolveram uma integração mais profunda entre suas duas soluções. Clientes de todos os tipos em todo o mundo adotaram a solução combinada de backup e recuperação CommVault Complete e StorageGRID.



== Sobre a CommVault e o StorageGRID

O software CommVault Complete Backup and Recovery é uma solução de gerenciamento de informações e dados integrada de nível empresarial, desenvolvida do zero em uma única plataforma e com uma base de código unificada. Todas as suas funções compartilham tecnologias de back-end, trazendo vantagens e benefícios incomparáveis de uma abordagem totalmente integrada para proteger, gerenciar e acessar seus dados. O software contém módulos para proteger, arquivar, analisar, replicar e pesquisar seus dados. Os módulos compartilham um conjunto comum de serviços de back-end e recursos avançados que interagem perfeitamente uns com os outros. A solução aborda todos os aspectos do gerenciamento de dados em sua empresa, ao mesmo tempo em que oferece escalabilidade infinita e controle sem precedentes de dados e informações.

O NetApp StorageGRID como uma categoria de nuvem CommVault é uma solução empresarial de storage de objetos para nuvem híbrida. Você pode implantá-lo em vários sites, seja em um dispositivo criado sob medida ou como uma implantação definida por software. O StorageGRID permite que você estabeleça políticas de gerenciamento de dados que determinem como os dados são armazenados e protegidos. A StorageGRID coleta as informações necessárias para desenvolver e aplicar políticas. Ele examina uma ampla gama de caraterísticas e necessidades, incluindo desempenho, durabilidade, disponibilidade, localização geográfica, longevidade e custo. Os dados são totalmente mantidos e protegidos à medida que se movem entre locais e à medida que envelhecem.

O mecanismo de política inteligente StorageGRID ajuda você a escolher uma das seguintes opções:

* Usar codificação de apagamento para fazer backup de dados em vários locais para resiliência.
* Copiar objetos para locais remotos para minimizar a latência e o custo da WAN.


Quando o StorageGRID armazena um objeto, você o acessa como um objeto, independentemente de onde ele esteja ou quantas cópias existem. Esse comportamento é crucial para a recuperação de desastres, porque com ele, mesmo que uma cópia de backup de seus dados esteja corrompida, o StorageGRID é capaz de restaurar seus dados.

Reter dados de backup em seu storage primário pode ser caro. Ao usar o NetApp StorageGRID, você libera espaço no storage primário migrando dados de backup inativos para o StorageGRID, enquanto aproveita as diversas funcionalidades do StorageGRID. O valor dos dados de backup muda ao longo do tempo, assim como o custo de armazená-los. O StorageGRID pode minimizar o custo do storage primário e aumentar a durabilidade dos dados.



== Principais recursos

Os principais recursos da plataforma de software CommVault incluem:

* Uma solução completa de proteção de dados compatível com todos os principais sistemas operacionais, aplicações e bancos de dados em servidores virtuais e físicos, sistemas nas, infraestruturas baseadas em nuvem e dispositivos móveis.
* Gerenciamento simplificado por meio de um único console: Você pode visualizar, gerenciar e acessar todas as funções e todos os dados e informações da empresa.
* Vários métodos de proteção, incluindo backup e arquivamento de dados, gerenciamento de snapshot, replicação de dados e indexação de conteúdo para e-Discovery.
* Gerenciamento eficiente de storage usando deduplicação em disco e storage de nuvem.
* Integração com matrizes de armazenamento NetApp, como AFF, FAS, NetApp HCI e e-Series, e sistemas de armazenamento de escalabilidade horizontal NetApp SolidFire. Integração também com o software NetApp Cloud Volumes ONTAP para automatizar a criação de cópias NetApp Snapshot indexadas e com reconhecimento de aplicações em todo o portfólio de storage da NetApp.
* Gerenciamento completo da infraestrutura virtual compatível com os principais hypervisors virtuais no local e plataformas de hyperscaler de nuvem pública.
* Recursos avançados de segurança para limitar o acesso a dados essenciais, fornecer recursos de gerenciamento granular e fornecer acesso de logon único para usuários do ative Directory.
* Gerenciamento de dados baseado em políticas que permite gerenciar seus dados com base nas necessidades empresariais, e não no local físico.
* Uma experiência de usuário final de ponta, capacitando seus usuários a proteger, encontrar e recuperar seus próprios dados.
* Automação orientada por API, permitindo que você use ferramentas de terceiros, como o vRealize Automation ou o Service Now, para gerenciar suas operações de proteção e recuperação de dados.


Para obter detalhes sobre workloads compatíveis, visite https://www.commvault.com/supported-technologies["Tecnologias compatíveis do CommVault"].



== Opções de backup

Ao implementar o software CommVault Complete Backup and Recovery com storage de nuvem, você tem duas opções de backup:

* Faça backup em um destino de disco primário e também faça backup de uma cópia auxiliar no armazenamento em nuvem.
* Fazer backup no storage de nuvem como destino principal.


No passado, o storage de objetos ou nuvem era considerado de baixa performance para ser usado no backup primário. O uso de um destino de disco primário permitiu que os clientes tivessem processos de backup e restauração mais rápidos e mantessem uma cópia auxiliar na nuvem como um backup inativo. O StorageGRID representa a próxima geração de storage de objetos. O StorageGRID oferece alta performance e taxa de transferência massiva, além de performance e flexibilidade além do que outros fornecedores de storage de objetos oferecem.

A tabela a seguir lista os benefícios de cada opção de backup com o StorageGRID:

[cols="1a,1a,1a"]
|===
|  | Backup primário para disco e uma cópia auxiliar para StorageGRID | Backup primário para StorageGRID 


 a| 
Desempenho
 a| 
Tempo de recuperação mais rápido, usando montagem em tempo real ou recuperação em tempo real: Ideal para workloads Tier0/Tier1.
 a| 
Não pode ser utilizado para operações de montagem em tempo real ou de recuperação em tempo real. Ideal para operação de restauração de streaming e para retenção de longo prazo.



 a| 
Arquitetura de implantação
 a| 
Usa o all-flash ou um disco giratório como primeira camada inicial de backup. StorageGRID é usado como um nível secundário.
 a| 
Simplifica a implantação usando o StorageGRID como destino de backup completo.



 a| 
Recursos avançados (restauração ao vivo)
 a| 
Suportado
 a| 
Não suportado

|===


== Onde encontrar informações adicionais

Para saber mais sobre as informações descritas neste documento, consulte os seguintes documentos e/ou sites:

* Centro de Documentação do StorageGRID 11,8 https://docs.netapp.com/us-en/storagegrid-118/[]
* Documentação do produto NetApp https://docs.netapp.com[]
* Documentação do CommVault https://documentation.commvault.com/2024/essential/index.html[]

