---
sidebar: sidebar 
permalink: technical-reports/commvault/solution-overview.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: Explore alguns casos de uso para configurações do StorageGRID implementadas pelos clientes e PELA TI DA NetApp. 
---
= Visão geral da solução testada
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
A solução testada combina as soluções CommVault e NetApp para criar uma solução conjunta poderosa.



== Configuração da solução

Na configuração do laboratório, o ambiente StorageGRID consistia em quatro dispositivos NetApp StorageGRID SG5712, um nó de administração principal virtual e um nó de gateway virtual. O dispositivo SG5712 é a opção de nível de entrada, uma configuração de linha de base. A escolha de opções de dispositivos de maior performance, como o NetApp StorageGRID SG5760 ou o SG6060, pode fornecer benefícios significativos de performance. Consulte o arquiteto de soluções da NetApp StorageGRID para obter assistência sobre o dimensionamento.

Na política de proteção de dados, o StorageGRID usa uma política de gerenciamento de ciclo de vida integrado (ILM) para gerenciar e proteger os dados. As regras do ILM são avaliadas em uma política de cima para baixo. Implementamos a política ILM mostrada na seguinte tabela:

[cols="1a,1a,1a"]
|===
| Regra ILM | Qualificadores | Comportamento de ingestão 


 a| 
Codificação de apagamento 2-1
 a| 
Objetos acima de 200KB
 a| 
Equilibrado



 a| 
2 cópia
 a| 
Todos os objetos
 a| 
Commit duplo

|===
A regra de cópia ILM 2 é a regra padrão. A regra de codificação de apagamento 2-1 foi aplicada para este teste a qualquer objeto 200KB ou maior. A regra padrão foi aplicada a objetos menores que 200KB. A aplicação das regras desta forma é uma melhor prática do StorageGRID.

Para obter detalhes técnicos sobre esse ambiente de teste, leia a seção Design da solução e práticas recomendadas no https://www.netapp.com/us/media/tr-4831.pdf["Proteção de dados com escalabilidade horizontal do NetApp com o CommVault"] relatório técnico.



== Especificações de hardware da StorageGRID

A tabela a seguir descreve o hardware NetApp StorageGRID usado neste teste. O dispositivo StorageGRID SG5712 com rede 10Gbps é a opção de nível de entrada e representa uma configuração de linha de base. Opcionalmente, o SG5712 pode ser configurado para rede 25GbpsG.

[cols="1a,1a,1a,1a,1a"]
|===
| Hardware | Quantidade | Disco | Capacidade utilizável | Rede 


 a| 
Aparelhos StorageGRID SG5712
 a| 
4
 a| 
48 x 4TB (HDD SAS near-line)
 a| 
136 TB
 a| 
10Gbps

|===
A escolha de opções de dispositivo de alta performance, como os dispositivos NetApp StorageGRID SG5760, SG6060 ou All Flash SGF6112, pode fornecer benefícios significativos de desempenho. Consulte o arquiteto de soluções da NetApp StorageGRID para obter assistência sobre o dimensionamento.



== Requisitos de software CommVault e StorageGRID

As tabelas a seguir listam os requisitos de software para o software CommVault e NetApp StorageGRID instalados no software VMware para nossos testes. Quatro gerenciadores de transmissão de dados do MediaAgent e um servidor CommServe foram instalados. No teste, a rede 10GbpsG foi implementada para a infraestrutura VMware. A tabela a seguir

A tabela a seguir lista todos os requisitos de sistema do software CommVault:

[cols="1a,1a,1a,1a,1a,1a"]
|===
| Componente | Quantidade | Armazenamento de dados | Tamanho | Total | Total de IOPS necessário 


 a| 
Servidor CommServe
 a| 
1
 a| 
SO
 a| 
500 GB
 a| 
500 GB
 a| 
n/a.



 a| 
 a| 
 a| 
SQL
 a| 
500 GB
 a| 
500 GB
 a| 
n/a.



 a| 
MediaAgent
 a| 
4
 a| 
CPU virtual (vCPU)
 a| 
16
 a| 
64
 a| 
n/a.



 a| 
 a| 
 a| 
RAM
 a| 
128 GB
 a| 
512
 a| 
n/a.



 a| 
 a| 
 a| 
SO
 a| 
500 GB
 a| 
2 TB
 a| 
n/a.



 a| 
 a| 
 a| 
Cache de índice
 a| 
2 TB
 a| 
8 TB
 a| 
Mais de 200 anos



 a| 
 a| 
 a| 
DDB
 a| 
2 TB
 a| 
8 TB
 a| 
200-80.000K

|===
No ambiente de teste, um nó de administrador principal virtual e um nó de gateway virtual foram implantados no VMware em um storage array do NetApp e-Series E2812. Cada nó estava em um servidor separado com os requisitos mínimos de ambiente de produção descritos na tabela a seguir:

A tabela a seguir lista os requisitos para nós de administração virtual do StorageGRID e nós de gateway:

[cols="1a,1a,1a,1a,1a"]
|===
| Tipo de nó | Quantidade | VCPU | RAM | Armazenamento 


 a| 
Nó de gateway
 a| 
1
 a| 
8
 a| 
24 GB
 a| 
100GB LUN para o SO



 a| 
Nó de administrador
 a| 
1
 a| 
8
 a| 
24 GB
 a| 
100GB LUN para o SO

200GB LUN para tabelas de nó Admin

200GB LUN para o log de auditoria do nó Admin

|===